#!/bin/sh

echo "-----------------------------------"
echo "Go"
go run go/parse.go

echo "-----------------------------------"
echo "Ruby"
ruby ruby/parse.rb

echo "-----------------------------------"
echo "Python"
python python/parse.py
rm -rf __pycache__

echo "-----------------------------------"
echo "Node"
node node/parse.js

echo "-----------------------------------"
echo "Java"
cd java
./run
